name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS region
        run: aws configure set region us-east-1

      - name: Build Docker image
        run: docker build -t app .

      - name: Tag Docker image
        run: docker tag app:latest 827061514539.dkr.ecr.us-east-1.amazonaws.com/app:latest

      - name: Deploy to AWS
        run: |
          aws configure set aws_access_key_id AKIA4BEFVGEVVAFNJGVQ
          aws configure set aws_secret_access_key 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
          aws configure set region us-east-1
          aws configure set output json
          # Elastic Beanstalk Deployment
          aws elasticbeanstalk create-application-version --application-name your-application-name --version-label your-version-label --source-bundle S3Bucket=your-bucket-name,S3Key=your-object-key
          aws elasticbeanstalk update-environment --environment-name your-environment-name --version-label your-version-label
          # Or ECS Deployment
          # Replace the commands below with your ECS deployment steps
          # aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
