name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: us-east-1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kcwitch/diaryapp:latest

      - name: Deploy to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          aws configure set default.output json

          # Elastic Beanstalk Deployment
          aws elasticbeanstalk create-application-version --region us-east-1 --application-name diaryapp --version-label your-version-label --source-bundle S3Bucket=your-bucket-name,S3Key=your-object-key
          aws elasticbeanstalk update-environment --environment-name your-environment-name --version-label your-version-label

          # Or ECS Deployment
          # Replace the commands below with your ECS deployment steps
          # aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
